version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - ${NGINX_HOST_PORT}:80
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.prod
      args:
        DOCKER_UID: ${DOCKER_UID:-0}
        DOCKER_GID: ${DOCKER_GID:-0}
        APP_ENV: ${APP_ENV:-local}
    tty: true
    stdin_open: true
    restart: unless-stopped
    command: sh /docker-entrypoint.sh
    volumes:
      - ./api/.env:/app/.env
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile.prod
      args:
        APP_ENV: ${APP_ENV:-local}
    tty: true         # docker run -t
    stdin_open: true  # docker run -i
    restart: unless-stopped
    ports:
      - ${CLIENT_HOST_PORT}:3000
    environment:
      NUXT_HOST: 0.0.0.0
    command: sh /docker-entrypoint.sh
    volumes:
      - ./client/.env:/app/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
